apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: sample-app-appset
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - name: staging
        path: environments/staging
        destNamespace: staging
      - name: prod
        path: environments/prod
        destNamespace: prod
  template:
    metadata:
      name: '{{name}}-sample-app'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/Jeandre-kotze/MCP-ARGO.git'
        targetRevision: master
        path: '{{path}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{destNamespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
